export default {
  en: {
    "/": "/en/",
    "accessibility-statement": "/en/accessibility-statement/",
    hyy: "/en/hyy/",
    isyy: "/en/isyy/",
    lyy: "/en/lyy/",
    trey: "/en/trey/",
    tyy: "/en/tyy/",
    aas: "/en/aas/",
    shs: "/en/shs/",
  },
  fi: {
    "/": "/",
    "accessibility-statement": "/saavutettavuusseloste/",
    "09bd303a": "/09bd303a/",
    hyy: "/hyy/",
    shs: "/shs/",
    isyy: "/isyy/",
    lyy: "/lyy/",
    trey: "/trey/",
    tyy: "/tyy/",
    aas: "/aas/",
  },
  sv: {
    "/": "/sv/",
    "accessibility-statement": "/sv/tillganglighetsutlatande/",
    hyy: "/sv/hus/",
    shs: "/sv/shs/",
    trey: "/sv/trey/",
    aas: "/sv/aas/",
  },
};
